# Generated by Django 4.1.1 on 2022-09-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField(null=True)),
                ('profile', models.CharField(max_length=23)),
                ('category', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('dob', models.DateField(auto_now_add=True)),
                ('pf', models.TextField(null=True)),
                ('bg', models.CharField(max_length=13)),
                ('content', models.TextField()),
                ('extra', models.TextField()),
                ('password', models.TextField(null=True)),
            ],
        ),
    ]
